### ISSUE TITLE
Login via Safari on iOS and Chrome on Android doesn’t work

### ISSUE THREAD

**Issue by jandreaucodes** [aunefyren/wrapperr#25] opened 2022-01-02 17:16 UTC
On Safari in iOS 15, clicking "login with Plex" just says "loading" and doesn't open the modal to authenticate. 

On Chrome in Android, it opens the authentication window, but then authentication fails and brings you back to the login screen. 

Authentication works fine on desktop.

**Comment by aunefyren** [comment] 2022-01-02 18:02
I am not sure, but I think the Android and iOs issues could be separate. Safari is a bitch to test for me, but I think the issue is Safari blocking pop up windows, as it is not a modal. Think there is a setting for this in the app.

As for Chrome on Android, that is what I use myself, so it should work. Does the pop up window state a successful login, but when it closes it prompts for a new login? This means the website is not accepting the cookie it just made. Last time i encountered this it was missing PHP packages (https://github.com/aunefyren/wrapperr/issues/24#issuecomment-997385711). But that should probably affect desktop as well?

**Comment by jandreaucodes** [comment] 2022-01-02 18:22
Looks like same issue on iPadOS 15, as well. Just sits on the button saying "Loading..."

**Comment by jandreaucodes** [comment] 2022-01-02 18:28
I double checked and I don't have anything blocking pop ups in iOS or iPadOS.

I'll have my friend with Android take another look. I believe she said it just didn't log her in, but closed the authorization window.

**Comment by jandreaucodes** [comment] 2022-01-02 18:35
I got iOS and iPadOS to work by restarting my host machine.

**Comment by aunefyren** [comment] 2022-01-02 18:39
> I got iOS and iPadOS to work by restarting my host machine.

That's good! This just means we need to figure out what might be causing issues on Android.

**Comment by aunefyren** [comment] 2022-07-04 19:57
Fixed in v3.0.0

**Closed by aunefyren** 2022-07-04 19:57 UTC
Labels: bug
